// ── Seed opportunities used as fallback when live sources aren't available ──
// These are realistic Indian student-focused opportunities spanning all 4 categories.

import type { Opportunity, Category } from "@/lib/types";

// Use a fixed reference point to avoid hydration mismatch
// (Date.now() differs between server render and client hydration)
const REF = new Date("2026-07-01T00:00:00Z").getTime();
const d = (days: number) => new Date(REF + days * 86400000).toISOString();
const ago = (days: number) => new Date(REF - days * 86400000).toISOString();
const VERIFIED = "2026-06-24T00:00:00Z";

export const SEED_OPPORTUNITIES: Opportunity[] = [
  {
    id: "seed:google-swe-intern",
    source: "seed",
    sourceLabel: "Google Careers",
    sourceUrl: "https://careers.google.com/jobs/results/?q=intern",
    category: "internship",
    title: "Google SWE Internship 2026",
    organization: "Google",
    summary: "12-week summer internship for students pursuing CS or related fields. Work on impactful projects.",
    imageUrl: undefined,
    logoUrl: undefined,
    location: "Bangalore, India",
    isRemote: false,
    tags: ["python", "cpp", "machine-learning", "data-analysis"],
    deadline: d(30),
    postedAt: ago(5),
    stipendMin: 80000,
    stipendMax: 120000,
    stipendPeriod: "month",
    currency: "INR",
    popularity: 15000,
    eligibility: { branches: ["computer-science", "information-technology", "electronics"], years: [2026, 2027] },
    lastVerified: VERIFIED,
  },
  {
    id: "seed:razorpay-intern",
    source: "seed",
    sourceLabel: "Razorpay",
    sourceUrl: "https://razorpay.com/careers/",
    category: "internship",
    title: "Razorpay Backend Engineering Intern",
    organization: "Razorpay",
    summary: "Build scalable payment infrastructure serving millions of businesses across India.",
    tags: ["go", "python", "docker", "kubernetes", "fintech"],
    deadline: d(14),
    postedAt: ago(3),
    stipendMin: 50000,
    stipendMax: 75000,
    stipendPeriod: "month",
    currency: "INR",
    popularity: 4200,
    eligibility: { branches: ["computer-science", "information-technology"], years: [2026, 2027] },
    lastVerified: VERIFIED,
  },
  {
    id: "seed:flipkart-grid",
    source: "seed",
    sourceLabel: "Unstop",
    sourceUrl: "https://unstop.com/hackathons/flipkart-grid-60",
    category: "hackathon",
    title: "Flipkart GRiD 6.0 — Software Development Challenge",
    organization: "Flipkart",
    summary: "India's largest e-commerce engineering challenge. Solve real-world problems at scale.",
    tags: ["machine-learning", "react", "nodejs", "data-analysis"],
    deadline: d(21),
    postedAt: ago(7),
    prizeAmount: 300000,
    currency: "INR",
    popularity: 22000,
    eligibility: { years: [2025, 2026, 2027] },
    lastVerified: VERIFIED,
  },
  {
    id: "seed:smart-india-hackathon",
    source: "seed",
    sourceLabel: "SIH",
    sourceUrl: "https://www.sih.gov.in/",
    category: "hackathon",
    title: "Smart India Hackathon 2026",
    organization: "Government of India",
    summary: "Nation-wide hackathon for students to solve pressing problems posed by government ministries.",
    tags: ["problem-solving", "iot", "machine-learning", "web-development"],
    deadline: d(45),
    postedAt: ago(10),
    prizeAmount: 100000,
    currency: "INR",
    popularity: 50000,
    eligibility: { citizenship: "IN" },
    lastVerified: VERIFIED,
  },
  {
    id: "seed:gsoc-2026",
    source: "seed",
    sourceLabel: "Google",
    sourceUrl: "https://summerofcode.withgoogle.com/",
    category: "competition",
    title: "Google Summer of Code 2026",
    organization: "Google",
    summary: "Contribute to open-source projects mentored by experienced developers worldwide.",
    tags: ["python", "javascript", "cpp", "go", "git"],
    deadline: d(60),
    postedAt: ago(14),
    stipendMin: 3000,
    stipendMax: 6600,
    stipendPeriod: "one-time",
    currency: "USD",
    popularity: 35000,
    lastVerified: VERIFIED,
  },
  {
    id: "seed:nsp-scholarship",
    source: "seed",
    sourceLabel: "National Scholarship Portal",
    sourceUrl: "https://scholarships.gov.in/",
    category: "scholarship",
    title: "National Scholarship Portal — Central Sector Scheme",
    organization: "Ministry of Education, India",
    summary: "Merit-based scholarship for students from economically weaker sections pursuing higher education.",
    tags: [],
    deadline: d(90),
    postedAt: ago(20),
    awardAmount: 20000,
    currency: "INR",
    popularity: 100000,
    eligibility: { citizenship: "IN", years: [2025, 2026, 2027, 2028] },
    lastVerified: VERIFIED,
  },
  {
    id: "seed:inspire-scholarship",
    source: "seed",
    sourceLabel: "DST India",
    sourceUrl: "https://online-inspire.gov.in/",
    category: "scholarship",
    title: "INSPIRE Scholarship for Higher Education",
    organization: "Dept of Science & Technology",
    summary: "Scholarship for top-performing students pursuing natural and basic science courses.",
    tags: ["data-analysis", "statistics"],
    deadline: d(75),
    postedAt: ago(15),
    awardAmount: 80000,
    currency: "INR",
    popularity: 25000,
    eligibility: { citizenship: "IN", branches: ["physics", "mathematics", "chemical", "biotechnology"] },
    lastVerified: VERIFIED,
  },
  {
    id: "seed:tata-scholarship",
    source: "seed",
    sourceLabel: "Tata Trusts",
    sourceUrl: "https://www.tatatrusts.org/",
    category: "scholarship",
    title: "Tata Capital Pankh Scholarship",
    organization: "Tata Capital",
    summary: "Financial support for meritorious students from underserved backgrounds across India.",
    tags: [],
    deadline: d(50),
    postedAt: ago(8),
    awardAmount: 50000,
    currency: "INR",
    popularity: 18000,
    eligibility: { citizenship: "IN" },
    lastVerified: VERIFIED,
  },
  {
    id: "seed:devpost-ethglobal",
    source: "seed",
    sourceLabel: "Devpost",
    sourceUrl: "https://ethglobal.devpost.com/",
    category: "hackathon",
    title: "ETHGlobal Bangkok 2026",
    organization: "ETHGlobal",
    summary: "36-hour in-person hackathon building the future of decentralized applications.",
    tags: ["blockchain", "ethereum", "solidity", "web3"],
    deadline: d(8),
    postedAt: ago(2),
    prizeAmount: 750000,
    currency: "USD",
    popularity: 8000,
    lastVerified: VERIFIED,
  },
  {
    id: "seed:codeforces-round",
    source: "seed",
    sourceLabel: "Codeforces",
    sourceUrl: "https://codeforces.com/contests",
    category: "competition",
    title: "Codeforces Round #950 (Div. 2)",
    organization: "Codeforces",
    summary: "Competitive programming contest open to all. Solve algorithmic problems in 2 hours.",
    tags: ["cpp", "problem-solving", "python"],
    deadline: d(3),
    postedAt: ago(1),
    popularity: 12000,
    lastVerified: VERIFIED,
  },
  {
    id: "seed:zerodha-intern",
    source: "seed",
    sourceLabel: "Zerodha",
    sourceUrl: "https://zerodha.com/careers/",
    category: "internship",
    title: "Zerodha Technology Intern",
    organization: "Zerodha",
    summary: "Work on India's largest stock trading platform. Focus on performance and scale.",
    tags: ["go", "python", "react", "fintech", "docker"],
    deadline: d(18),
    postedAt: ago(4),
    stipendMin: 60000,
    stipendMax: 80000,
    stipendPeriod: "month",
    currency: "INR",
    popularity: 6500,
    eligibility: { branches: ["computer-science", "information-technology"], years: [2026, 2027] },
    lastVerified: VERIFIED,
  },
  {
    id: "seed:daad-scholarship",
    source: "seed",
    sourceLabel: "DAAD",
    sourceUrl: "https://www.daad.in/en/",
    category: "scholarship",
    title: "DAAD Scholarship for Development-Related Studies",
    organization: "DAAD Germany",
    summary: "Fully funded Master's/PhD scholarships in Germany for students from developing countries.",
    tags: [],
    deadline: d(120),
    postedAt: ago(30),
    awardAmount: 0,
    currency: "EUR",
    popularity: 15000,
    eligibility: { citizenship: "IN" },
    lastVerified: VERIFIED,
  },
  {
    id: "seed:codechef-starters",
    source: "seed",
    sourceLabel: "CodeChef",
    sourceUrl: "https://www.codechef.com/contests",
    category: "competition",
    title: "CodeChef Starters 150",
    organization: "CodeChef",
    summary: "Rated programming contest for all divisions. Hone your problem-solving skills.",
    tags: ["cpp", "python", "problem-solving"],
    deadline: d(5),
    postedAt: ago(1),
    popularity: 8000,
    lastVerified: VERIFIED,
  },
  {
    id: "seed:microsoft-intern",
    source: "seed",
    sourceLabel: "Microsoft",
    sourceUrl: "https://careers.microsoft.com/",
    category: "internship",
    title: "Microsoft Explore Intern — India",
    organization: "Microsoft",
    summary: "Rotational internship across PM, Design and SWE for first/second year students.",
    tags: ["typescript", "react", "azure", "machine-learning"],
    deadline: d(40),
    postedAt: ago(6),
    stipendMin: 70000,
    stipendMax: 100000,
    stipendPeriod: "month",
    currency: "INR",
    popularity: 20000,
    eligibility: { branches: ["computer-science", "information-technology", "electronics"], years: [2027, 2028] },
    lastVerified: VERIFIED,
  },
  {
    id: "seed:devfolio-hackathon",
    source: "seed",
    sourceLabel: "Devfolio",
    sourceUrl: "https://devfolio.co/hackathons",
    category: "hackathon",
    title: "HackIndia 2026 — National Hackathon",
    organization: "HackIndia",
    summary: "India's largest student hackathon series with regional and national rounds.",
    tags: ["web-development", "machine-learning", "blockchain", "iot"],
    deadline: d(25),
    postedAt: ago(5),
    prizeAmount: 500000,
    currency: "INR",
    popularity: 30000,
    lastVerified: VERIFIED,
  },
  {
    id: "seed:aicte-pragati",
    source: "seed",
    sourceLabel: "AICTE",
    sourceUrl: "https://www.aicte-india.org/schemes/students-development-schemes",
    category: "scholarship",
    title: "AICTE Pragati Scholarship for Girls",
    organization: "AICTE",
    summary: "Scholarship for girl students in AICTE-approved technical degree programs.",
    tags: [],
    deadline: d(65),
    postedAt: ago(12),
    awardAmount: 50000,
    currency: "INR",
    popularity: 30000,
    eligibility: { gender: "female", citizenship: "IN" },
    lastVerified: VERIFIED,
  },
];

/** Get count per category */
export function getCategoryCounts(): Record<Category, number> {
  const counts: Record<Category, number> = {
    internship: 0,
    scholarship: 0,
    competition: 0,
    hackathon: 0,
  };
  for (const o of SEED_OPPORTUNITIES) {
    counts[o.category]++;
  }
  return counts;
}
